[green_agent]
agentbeats_id = "019bb789-1010-7860-99ee-1ec2bd55a7e5"
env = { API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[purple_agent]
agentbeats_id = "019bb79f-e796-7ea3-8dab-21036df3d412"
env = { API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
name = "Green"
agent = "green_agent"

[[participants]]
name = "Purple"
agent = "purple_agent"

[config]
domain = "wireless"

# Each entry defines one evaluation round

test_rounds = [
{ attacker = "Green", defender = "Purple" }
]
